### ISSUE TITLE
"An accessor cannot be declared in an ambient context" when compiling Typescript

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#316]
Since upgrading to version 17 (2.0.0-preview017.2 specifically) from 16, I've started getting a ton of these Typescript compilation errors when compiling my project:

```
projects/foo/src/generated/index.d.ts:16240:17 - error TS1086: An accessor cannot be declared in an ambient context.

16240     private get _document();
```

I'm able to "resolve" the issue by turning on the `skipLibCheck` flag when compiling, but this feels hacky and wasn't necessary before.

(Just to clarify, my photon client is generated into a specific directory as specified in my prisma file, not `node_modules`)

**Comment by pantharshit00** [comment]
Can you provide a minimal reproduction for this, I am unable to reproduce this from the starters.

**Comment by artemzakharov** [comment]
Nevermind, I investigated the actual error it was throwing, and it appears to be related to some recent updates to Typescript itself - I updated my project's Typescript version to 3.7.0 based on some recommendations, and that fixed the issue.
